scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117348.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117349.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117350.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117351.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117352.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117353.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117355.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117356.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117357.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117358.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117359.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117362.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117363.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117364.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117365.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117366.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117367.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117368.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117429.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117430.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117431.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117432.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117433.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117434.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117435.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117444.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117445.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117446.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117447.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117448.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117543.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117544.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117545.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117546.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117547.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117548.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117549.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117550.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117551.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117552.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117452.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117739.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117405.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117406.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117408.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117409.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117410.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117411.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117412.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117511.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117512.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117513.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117514.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117515.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117516.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117517.root .
scp hocai@lxplus.cern.ch:/eos/experiment/ntof/processing/official/done/run117518.root .
